@mod09API_HostAddress = http://localhost:5046

GET {{mod09API_HostAddress}}/wf/
Accept: application/json

###
GET {{mod09API_HostAddress}}/wf/1


###
POST {{mod09API_HostAddress}}/wf/
Content-Type: application/json

{
  "date": "2024-06-01",
  "temperatureC": 25,
  "summary": "Warm"
}


###
GET {{mod09API_HostAddress}}/api/MeetingRooms

###
GET {{mod09API_HostAddress}}/api/MeetingRooms/1

###
POST {{mod09API_HostAddress}}/api/MeetingRooms
Content-Type: application/json

{  
  "name": "台北101",
  "size": 100,
  "projector": true,
  "tv": true
}

###
PUT {{mod09API_HostAddress}}/api/MeetingRooms/6
Content-Type: application/json

{  
  "id": 6,  "name": "台北101",
  "size": 200,
  "projector": true,
  "tv": true
}

###
DELETE {{mod09API_HostAddress}}/api/MeetingRooms/6
