@mod09API_HostAddress = http://localhost:5046

GET {{mod09API_HostAddress}}/wf/
Accept: application/json

###
GET {{mod09API_HostAddress}}/wf/1


###
POST {{mod09API_HostAddress}}/wf/
Content-Type: application/json

{
  "date": "2024-06-01",
  "temperatureC": 25,
  "summary": "Warm"
}


###
GET {{mod09API_HostAddress}}/api/MeetingRooms
